name: check

on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read # リポジトリコンテンツの読み取り

jobs:
  nix-flake-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
        with:
          extra_nix_config: |
            accept-flake-config = true
      - run: nix flake check

  format: # `nix flake check`で実行される`nix fmt`で対応していない範囲のフォーマットチェックを行う。
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
        with:
          extra_nix_config: |
            accept-flake-config = true
      - name: terraform validate
        run: nix run '.#terraform-validate'
